MovieStore/WebUI/Controllers/ReviewsController.cs
using Services.Interfaces;
using Services.Messaging;
using Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewsService _reviewsService;

        public ReviewsController(IReviewsService reviewsService)
        {
            _reviewsService = reviewsService;
        }

        public ActionResult Index()
        {
            var reviews = _reviewsService.GetReviews();

            return View(reviews);
        }

        public ActionResult AddReview(int movieId, string movieTitle)
        {
            var model = new AddReviewViewModel
            {
                MovieId = movieId,
                MovieTitle = movieTitle
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddReview(AddReviewViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var request = new GetAddReviewRequest { Review = model };

            var response = _reviewsService.AddReview(request);

            if (!response.IsSuccess)
                return View(model);

            return RedirectToAction("Details", "Home", new { movieId = model.MovieId });
        }
    }
}

MovieStore/WebUI/Views/Shared/_CartSummary.cshtml
@model DomainModel.CartSummary

<div id="cart-summary">
    Ilość filmów w koszyku: @Model.TotalItems | Całkowity koszt: @Model.TotalPrice | @Html.ActionLink("Koszyk", "Index", "Cart")
</div>

MovieStore/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Świat filmów", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ostatnie recenzje", "Index", "Reviews")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container">
        @Html.Action("CartSummary", "Cart")
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Świat filmów</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>